### ISSUE TITLE
Fine grain logging via env vars

### ISSUE THREAD

**Issue by mrister** [dial-once/node-microservice-boot#17]
## Problem
Sometimes we need to log specific information more heavily to debug things and sometimes we want to turn off logging inside a client project. The easiest approach for this over env vars because it requires the least code interventions.

## Requirement
We need to support:
-  on/off for logging, on/off per logging source (e.g. on/off for logentries, on/off for console, etc. )
- set logging level global and per source (e.g. set logging level to error for all, just set error for logentries and debug for console and etc)
- log per wildcard: (since we should have consistent logging structure including module and functions this should be possible. for instance `service-test:middleware*` should log only from those logging statements in module service test submodule (dir) middleware )
- all of the above should be controllable over env vars and documented and tested

**Comment by Spring3** [comment]
Done in [logtify](https://github.com/dial-once/node-logtify)
