### ISSUE TITLE
Error on logger should forward error to bug reporter

### ISSUE THREAD

**Issue by PuKoren** [dial-once/node-microservice-boot#8]
This way we will be able to only uses logger, and any error/warning will be sent to the bug reporter with the appropriate tagging.

So, no need to require anymore the but reporter and do logger.error, then reporter.notify, etc.

Just handle your logging and everything is smooth.

What do you think guys?

@ky23 @mrister @jkernech

**Comment by mrister** [comment]
I like it! Any ideas on implementation ? Exporting a modified logger that will just trigger botifier on error. Is it good for every use case? (perhaps make that the default option but with ability to override if needed)

**Comment by PuKoren** [comment]
About implementation:

With winston it is fairly easy to add some kind of "middleware" for log processing, as we do today to append the HOSTNAME env var to each log payload: https://github.com/dial-once/node-microservice-boot/blob/develop/src/winston.js#L20

We can add a check in the rewriter, to use the botifier when level is error/warn.

I think it is pretty useful in every use case, I don't see any case where one would want to prevent error reporting using this module, but an option to disable it wont be to hard to add in the same time

**Comment by mrister** [comment]
OK, sounds great!

**Comment by ky23** [comment]
@PuKoren Great idea, but i agree with @mrister. It will be enabled by default, and it should let us the ability to disable it.

And also disable it for the current log message, something like `looger.error('Error message', { current: false})` so it will do it for all log except this one.

It could be useful for testing
